const requests = {
  TrendingList: "/api/trending/trending-list",
  HotList: "/api/hot/hot-list",
  NewList: "/api/new/new-list",
  fetchAmazonList: "/api/amazon/amazon-list",
  fetchMicrosoftList: "/api/microsoft/microsoft-list",
  fetchGoogleList: "/api/google/google-list",
  fetchTeslaList: "/api/tesla/tesla-list",
  fetchAppleList: "/api/apple/apple-list",
  fetchFacebookList: "/api/facebook/facebook-list",
  fetchPrivacyList: "/api/privacy/privacy-list",
  fetchCyberSecurityList: "/api/cybersecurity/cybersecurity-list",
  fetchNetflixList: "/api/netflix/netflix-list",
  fetchSportsList: "/api/sports/sports-list",
  fetchTelevisionList: "/api/television/television-list",
  fetchFilmsList: "/api/films/films-list",
  fetchGamingList: "/api/gaming/gaming-list",
  PhonesList: "/api/phones/phones-list",
  LaptopsList: "/api/laptops/laptops-list",
  CamerasList: "/api/cameras/cameras-list",
  HeadphonesList: "/api/headphones/headphones-list",
  SpeakersList: "/api/speakers/speakers-list",
  YoutubeList: "/api/youtube/youtube-list",
  InstagramList: "/api/instagram/instagram-list",
  LinkedinList: "/api/linkedin/linkedin-list",
  TwitterList: "/api/twitter/twitter-list",
  NasaList: "/api/nasa/nasa-list",
  Spacex: "/api/spacex/spacex-list",
  Health: "/api/health/health-list",
  Energy: "/api/energy/energy-list",
  Environment: "/api/environment/environment-list",
  More: "/api/more/more-list",
};

export default requests;
